# Generated by Django 4.1.2 on 2022-11-01 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import CaCatHead.core.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('problem', '__latest__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, verbose_name='代码')),
                ('language', models.CharField(max_length=32, verbose_name='程序语言')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('judged', models.DateTimeField(blank=True, null=True, verbose_name='评测时间')),
                ('verdict', models.CharField(default=CaCatHead.core.constants.Verdict['Waiting'], max_length=32,
                                             verbose_name='提交状态和判题结果')),
                ('score', models.IntegerField(default=0, verbose_name='总分')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='返回详情')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user',
                                             to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='problem',
                                              to='problem.problem', verbose_name='所属题目')),
                ('repository',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='repository',
                                   to='problem.problemrepository', verbose_name='所属题库')),
            ],
            options={
                'verbose_name': '提交信息',
                'verbose_name_plural': '提交信息列表',
                'db_table': 'submission',
            },
        ),
    ]
