# Generated by Django 4.1.2 on 2022-11-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created', '-judged', '-score', '-id'), 'verbose_name': '提交信息',
                     'verbose_name_plural': '提交信息列表'},
        ),
        migrations.AddField(
            model_name='submission',
            name='code_length',
            field=models.IntegerField(default=0, verbose_name='代码长度'),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_used',
            field=models.IntegerField(default=0, verbose_name='消耗内存'),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_used',
            field=models.IntegerField(default=0, verbose_name='消耗时间'),
        ),
    ]
