# Generated by Django 4.1.2 on 2023-01-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestsubmission',
            options={'ordering': ('-created', '-relative_time', '-score'), 'verbose_name': '比赛提交信息',
                     'verbose_name_plural': '比赛提交信息列表'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created', '-score'), 'verbose_name': '提交信息',
                     'verbose_name_plural': '提交信息列表'},
        ),
        migrations.AddIndex(
            model_name='contestsubmission',
            index=models.Index(fields=['repository'], name='contest_sub__repo_index'),
        ),
        migrations.AddIndex(
            model_name='contestsubmission',
            index=models.Index(fields=['repository', 'owner'], name='contest_sub__repo_owner_index'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['repository'], name='sub__repo_index'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['repository', 'owner'], name='sub__repo_owner_index'),
        ),
    ]
