# Generated by Django 4.1.2 on 2023-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('submission', '0002_alter_contestsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='code',
            field=models.TextField(blank=True, max_length=65535, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, max_length=65535, verbose_name='代码'),
        ),
    ]
