# Generated by Django 4.1.2 on 2023-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('submission', '0004_contestsubmission_contest_sub__verdict_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
