version: '3.9'

services:
  nginx:
    build: ./deploy/nginx
    container_name: cacathead_nginx
    restart: always
    depends_on:
      - server
      - app
    networks:
      - cat_net
    volumes:
      - ./.cacathead/logs/nginx:/var/log/nginx
      - ./.cacathead/static:/var/www/cacathead/static
      - ./deploy/nginx/cert:/root/cert
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Shanghai

  app:
    build:
      context: ./
      dockerfile: ./deploy/app/Dockerfile
    container_name: cacathead_app
    restart: always
    depends_on:
      - server
    networks:
      - cat_net
    environment:
      TZ: Asia/Shanghai
    # ports:
    #   - '3333:3333'

  server:
    build:
      context: ./
      dockerfile: ./deploy/server/Dockerfile
    container_name: cacathead_server
    depends_on:
      - postgresql
      - redis
      - rabbitmq
      - minio
    privileged: true
    restart: on-failure
    entrypoint: ./docker-entrypoint.sh
    command:
      - server
    # ports:
    #   - '8000:8000'
    networks:
      - cat_net
    volumes:
      - ./deploy/server/cacathead.yml:/root/CaCatHead/cacathead.yml
      - ./.cacathead/testcases:/root/testcases
      - ./.cacathead/static:/root/CaCatHead/static
    secrets:
      - db_pass
      - redis_pass
      - minio_pass
      - rmq_pass
    environment:
      WAIT_HOSTS: postgresql:5432  # See https://github.com/ufoscout/docker-compose-wait
    env_file:
      - ./deploy/server/.env

  judge:
    build:
      context: ./
      dockerfile: ./deploy/server/Dockerfile
    container_name: cacathead_judge
    depends_on:
      - postgresql
      - redis
      - rabbitmq
      - minio
      - server
    privileged: true
    restart: on-failure
    entrypoint: ./docker-entrypoint.sh
    command:
      - judge
    networks:
      - cat_net
    volumes:
      - ./deploy/server/cacathead.yml:/root/CaCatHead/cacathead.yml
      - ./.cacathead/checkers:/root/checkers
      - ./.cacathead/testcases:/root/testcases
      - ./.cacathead/logs/catj:/root/catj/logs
    secrets:
      - db_pass
      - redis_pass
      - minio_pass
      - rmq_pass
    environment:
      WAIT_HOSTS: rabbitmq:5672  # See https://github.com/ufoscout/docker-compose-wait
    env_file:
      - ./deploy/server/.env

  backup:
    build:
      context: ./
      dockerfile: ./deploy/backup/Dockerfile
    container_name: cacathead_backup
    depends_on:
      - postgresql
    restart: always
    entrypoint: ./docker-entrypoint.sh
    networks:
      - cat_net
    volumes:
      - ./.cacathead/backup:/root/backup
    secrets:
      - db_pass
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: postgresql:5432  # See https://github.com/ufoscout/docker-compose-wait
    env_file:
      - ./deploy/server/.env

  postgresql:
    image: postgres:15.1
    container_name: cacathead_postgres
    restart: always
    networks:
      - cat_net
    ports:
      - '5432:5432'
    volumes:
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.cacathead/database:/var/lib/postgresql/data
    secrets:
      - db_pass
    environment:
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
      POSTGRES_DB: cacathead
      POSTGRES_USER: root
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pass

  minio:
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    container_name: cacathead_minio
    command: server /data
    # command: server --console-address ":9090" /data
    restart: always
    networks:
      - cat_net
    ports:
      - '9000:9000'
      # - '9090:9090'
    volumes:
      - ./.cacathead/minio:/data
    secrets:
      - minio_pass
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_pass

  redis:
    image: redis:7.0.5-alpine
    container_name: cacathead_redis
    restart: always
    networks:
      - cat_net
    secrets:
      - redis_pass
    volumes:
      - ./.cacathead/redis:/data
    environment:
      TZ: Asia/Shanghai

  rabbitmq:
    # image: rabbitmq:3.11.0
    image: rabbitmq:management
    container_name: cacathead_rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - cat_net
    volumes:
      - ./deploy/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      TZ: Asia/Shanghai

networks:
  cat_net:

secrets:
  db_pass:
    file: ./deploy/password/db_pass.txt
  redis_pass:
    file: ./deploy/password/redis_pass.txt
  minio_pass:
    file: ./deploy/password/minio_pass.txt
  rmq_pass:
    file: ./deploy/password/rmq_pass.txt
