# Generated by Django 4.1.2 on 2023-01-13 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('sort_time', models.DateTimeField(verbose_name='排序时间')),
                ('is_home', models.BooleanField(default=False, verbose_name='是否在首页')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL,
                                            verbose_name='发布者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告列表',
                'db_table': 'post',
                'ordering': ('-sort_time',),
            },
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='公告内容')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content',
                                              to='post.post', verbose_name='公告')),
            ],
            options={
                'verbose_name': '公告内容',
                'verbose_name_plural': '公告内容',
                'db_table': 'post_content',
            },
        ),
    ]
