# Generated by Django 4.1.2 on 2022-11-02 17:52

from django.core.management import call_command
from django.db import migrations


def load_fixture(_apps, _schema_editor):
    call_command('loaddata', 'post.json', app_label='post')


class Migration(migrations.Migration):
    dependencies = [
        ('user', '__latest__'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
