# Generated by Django 4.1.2 on 2022-11-12 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0002_init_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcontent',
            options={'verbose_name': '公告内容', 'verbose_name_plural': '公告内容'},
        ),
    ]
