# Generated by Django 4.1.2 on 2023-01-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0002_init_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='是否在首页'),
        ),
    ]
