# Generated by Django 4.1.2 on 2023-01-07 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0003_alter_postcontent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-sort_time',), 'verbose_name': '公告', 'verbose_name_plural': '公告列表'},
        ),
    ]
