# Generated by Django 4.1.2 on 2023-01-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sort_time',
            field=models.DateTimeField(verbose_name='排序时间'),
        ),
    ]
