### Hello world
GET http://127.0.0.1:8000/api/ping

### Sync server time
GET http://127.0.0.1:8000/api/sync?timestamp={{$timestamp}}

### List judge nodes
GET http://127.0.0.1:8000/api/judge/nodes

### Register
POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json

{
  "username": "world",
  "email": "world@example.com",
  "password": "12345678"
}

### Login root
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "username": "root",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.token); %}

### Login world
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "username": "world",
  "password": "12345678"
}

> {% client.global.set("auth_token", response.body.token); %}

### Logout
POST http://127.0.0.1:8000/api/auth/logout
Authorization: Token {{auth_token}}

### Profile
GET http://127.0.0.1:8000/api/user/profile
Authorization: Token {{auth_token}}

### Login validate error
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
  "username": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  "password": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}