# Generated by Django 4.1.2 on 2022-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('repo', models.CharField(default='cppexam', max_length=20, verbose_name='题目类型')),
                ('label', models.CharField(max_length=45, null=True, unique=True, verbose_name='题目编号')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='题目描述')),
                ('inputdescription', models.TextField(blank=True, null=True, verbose_name='输入描述')),
                ('outputdescription', models.TextField(blank=True, null=True, verbose_name='输出描述')),
                ('inputsample', models.TextField(blank=True, null=True, verbose_name='输入样例')),
                ('outputsample', models.TextField(blank=True, null=True, verbose_name='输出样例')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='解答提示')),
                ('source', models.TextField(blank=True, null=True, verbose_name='题目来源')),
                ('timelimit', models.IntegerField(default=1000, verbose_name='时间限制')),
                ('memorylimit', models.IntegerField(default=262144, verbose_name='内存限制')),
                ('score', models.IntegerField(default=0, verbose_name='题目总分')),
                ('level', models.IntegerField(default=3, verbose_name='题目难度')),
                ('testdata_count', models.IntegerField(default=0, verbose_name='用例数目')),
                ('testdata_score', models.TextField(blank=True, null=True, verbose_name='用例分数')),
                ('is_public', models.BooleanField(default=True, help_text='该项被选择后，题目将会被所有人看到，如果不选择则题目只能被超级用户和管理员看到.', verbose_name='是否公开')),
            ],
            options={
                'verbose_name': '题目信息',
                'verbose_name_plural': '题目列表',
                'db_table': 'problems',
            },
        ),
    ]
