# Generated by Django 4.1.2 on 2022-10-30 10:09

from django.db import migrations

from CaCatHead.core.constants import MAIN_PROBLEM_REPOSITORY
from CaCatHead.problem.models import ProblemRepository


def init_main_problem_repository(_apps, _schema_editor):
    """
    初始化主题库
    """
    main_repo = ProblemRepository(name=MAIN_PROBLEM_REPOSITORY, is_public=False)
    main_repo.save()


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_main_problem_repository)
    ]
