# Generated by Django 4.1.2 on 2023-01-10 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0002_init_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('repository', 'display_id'), 'verbose_name': '题目信息',
                     'verbose_name_plural': '题目列表'},
        ),
    ]
