# Generated by Django 4.1.2 on 2023-01-13 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0004_rename_repo_display_id_index_problem__repo_display_id_index_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('repository', 'display_id')},
        ),
    ]
