# Generated by Django 4.1.2 on 2023-01-14 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0005_alter_problem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(
                    choices=[('checker', 'Checker'), ('generator', 'Generator'), ('validator', 'Validator'),
                             ('solution', 'Solution')], max_length=32, verbose_name='代码类型')),
                ('code', models.TextField(blank=True, verbose_name='代码')),
                ('code_length', models.IntegerField(default=0, verbose_name='代码长度')),
                ('language', models.CharField(max_length=32, verbose_name='程序语言')),
                ('extra_info', models.JSONField(default=dict, verbose_name='其他信息')),
            ],
            options={
                'verbose_name': '题目代码',
                'verbose_name_plural': '题目代码列表',
                'db_table': 'source_code',
            },
        ),
        migrations.AddField(
            model_name='problemjudge',
            name='checker',
            field=models.CharField(
                choices=[('custom', 'Custom'), ('fcmp', 'Fcmp'), ('hcmp', 'Hcmp'), ('lcmp', 'Lcmp'), ('ncmp', 'Ncmp'),
                         ('nyesno', 'Nyesno'), ('rcmp4', 'Rcmp4'), ('rcmp6', 'Rcmp6'), ('rcmp9', 'Rcmp9'),
                         ('wcmp', 'Wcmp'), ('yesno', 'Yesno')], default='lcmp', max_length=64, verbose_name='checker'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(
                choices=[('classic_score', 'Score'), ('classic_ac', 'Ac'), ('interactive', 'Interactive'),
                         ('custom', 'Custom')], default='classic_ac', max_length=32, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='problemjudge',
            name='problem_type',
            field=models.CharField(
                choices=[('classic_score', 'Score'), ('classic_ac', 'Ac'), ('interactive', 'Interactive'),
                         ('custom', 'Custom')], default='classic_ac', max_length=32, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='problemjudge',
            name='custom_checker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='problem_judge_custom_checker', to='problem.sourcecode',
                                    verbose_name='自定义 Checker'),
        ),
    ]
