# Generated by Django 4.1.2 on 2023-01-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0006_sourcecode_problemjudge_checker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemjudge',
            name='testcase_version',
            field=models.IntegerField(default=0, verbose_name='测试用例版本'),
        ),
    ]
