# Generated by Django 4.1.2 on 2023-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problem', '0007_problemjudge_testcase_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecode',
            name='code',
            field=models.TextField(blank=True, max_length=65535, verbose_name='代码'),
        ),
    ]
