# Generated by Django 4.1.2 on 2022-11-12 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppermission',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'default_permissions': ()},
        ),
    ]
