# Generated by Django 4.1.2 on 2023-01-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgenode',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='节点名称'),
        ),
    ]
