# Generated by Django 4.1.2 on 2022-12-20 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('problem', '0002_init_repository'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('freeze_time', models.DateTimeField(blank=True, default=None, verbose_name='封榜时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('password', models.CharField(blank=True, default=None, max_length=256, verbose_name='注册密码')),
                ('extra_info', models.JSONField(default=dict, verbose_name='其他信息')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL,
                                            verbose_name='创建者')),
                ('problem_repository',
                 models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='problem.problemrepository',
                                   verbose_name='比赛题库')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛列表',
                'db_table': 'contest',
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('extra_info', models.JSONField(default=dict, verbose_name='其他信息')),
                ('members',
                 models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='队员')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                            verbose_name='队长')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍列表',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('extra_info', models.JSONField(default=dict, verbose_name='其他信息')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest',
                                              verbose_name='所属比赛')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.team',
                                           verbose_name='注册队伍')),
            ],
            options={
                'verbose_name': '比赛注册信息',
                'verbose_name_plural': '比赛注册信息列表',
                'db_table': 'contest_registration',
            },
        ),
    ]
