# Generated by Django 4.1.2 on 2023-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='type',
            field=models.CharField(default='icpc', max_length=64, verbose_name='比赛类型'),
        ),
    ]
