# Generated by Django 4.1.2 on 2023-01-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_team_single_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rating',
            field=models.IntegerField(default=1500, verbose_name='Rating'),
        ),
        migrations.CreateModel(
            name='RatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='原 Rating')),
                ('delta', models.IntegerField(verbose_name='Rating 变化量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest', verbose_name='比赛')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': 'Rating 日志',
                'verbose_name_plural': 'Rating 日志列表',
                'db_table': 'rating_log',
            },
        ),
    ]
