# Generated by Django 4.1.2 on 2023-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0002_contest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='freeze_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='封榜时间'),
        ),
    ]
