# Generated by Django 4.1.2 on 2023-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0003_alter_contest_freeze_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='注册密码'),
        ),
    ]
