# Generated by Django 4.1.2 on 2023-01-04 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0004_alter_contest_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ('-start_time',), 'verbose_name': '比赛', 'verbose_name_plural': '比赛列表'},
        ),
        migrations.AlterModelOptions(
            name='contestregistration',
            options={'ordering': ('-score', 'dirty'), 'verbose_name': '比赛注册信息',
                     'verbose_name_plural': '比赛注册信息列表'},
        ),
        migrations.AddField(
            model_name='contestregistration',
            name='dirty',
            field=models.IntegerField(default=0, verbose_name='罚时'),
        ),
        migrations.AddField(
            model_name='contestregistration',
            name='score',
            field=models.IntegerField(default=0, verbose_name='得分'),
        ),
        migrations.AddField(
            model_name='contestregistration',
            name='standings',
            field=models.JSONField(default=dict, verbose_name='排名信息'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contest_owner',
                                    to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
