# Generated by Django 4.1.2 on 2023-01-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0005_alter_contest_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contestregistration',
            index=models.Index(fields=['contest', 'team'], name='contest_team_index'),
        ),
    ]
