# Generated by Django 4.1.2 on 2023-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0007_alter_contest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='settings',
            field=models.JSONField(default={'view_standings': True, 'view_submissions_after_contest': False},
                                   verbose_name='比赛设置'),
        ),
    ]
