# Generated by Django 4.1.2 on 2023-01-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0008_contest_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestregistration',
            options={'ordering': ('-score', 'dirty', '-is_participate'), 'verbose_name': '比赛注册信息',
                     'verbose_name_plural': '比赛注册信息列表'},
        ),
        migrations.AddField(
            model_name='contestregistration',
            name='is_participate',
            field=models.BooleanField(default=False, verbose_name='是否参加比赛'),
        ),
    ]
