# Generated by Django 4.1.2 on 2023-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0009_alter_contestregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='settings',
            field=models.JSONField(default={}, verbose_name='比赛设置'),
        ),
    ]
