# Generated by Django 4.1.2 on 2023-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0010_alter_contest_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, default=str, verbose_name='比赛描述信息'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='settings',
            field=models.JSONField(default=dict, verbose_name='比赛设置'),
        ),
    ]
