# Generated by Django 4.1.2 on 2022-10-30 19:02
from django.contrib.auth.models import Group
from django.db import migrations

from CaCatHead.core.constants import NJUST_ICPC_GROUP
from CaCatHead.core.tests import init_superuser as _init_superuser


def init_team_group(_apps, _schema_editor):
    """
    初始化集训队成员 Group
    """
    team_group = Group(name=NJUST_ICPC_GROUP)
    team_group.save()


def init_superuser(_apps, _schema_editor):
    """
    初始化超级用户
    """
    _init_superuser()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_superuser),
        migrations.RunPython(init_team_group),
    ]
