# Generated by Django 4.1.2 on 2023-02-23 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('key', models.CharField(max_length=512, primary_key=True, serialize=False, verbose_name='Key')),
                ('login_ip', models.CharField(max_length=64, verbose_name='登录 IP')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user_agent', models.CharField(max_length=512, verbose_name='登录 User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_auth_token',
                                           to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': '用户 Token',
                'verbose_name_plural': '用户 Token 列表',
                'db_table': 'user_token',
            },
        ),
    ]
