# Generated by Django 4.1.2 on 2023-03-02 11:47

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='expiry_time',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 11, 47, 43, 348640, tzinfo=datetime.timezone.utc),
                verbose_name='过期时间'),
            preserve_default=False,
        ),
    ]
