# Generated by Django 4.1.2 on 2023-01-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_userinfo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='rank',
            field=models.CharField(default='newbie', max_length=32, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='rating',
            field=models.IntegerField(default=None, null=True, verbose_name='Rating'),
        ),
    ]
